---
abstract: 'guess an appropriate column type for a set of data'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Type-Guess
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
  strict: 0
resources:
  repository: http://github.com/Corion/sql-type-guess
version: 0.01
